### ISSUE TITLE
[Browser build] Asynchronous Module Definition

### ISSUE THREAD

**Issue by jvduf** [indexzero/broadway#11]
Hi @mmalecki @pksunkara 

Can we make builds that comply with the Asynchronous Module Definition?

Something like:

```
  if (typeof define === 'function' && define.amd) {
    define(function() { return App; });
  } else {
    exports.App = App;
  }
```

Should be an easy fix.. right?

**Comment by indexzero** [comment]
A lot has changed in [`v1.0.0`](https://github.com/indexzero/broadway/pull/54), so I'm going to close this. Also: hi @jvduf :smile:
