### ISSUE TITLE
App.prototype.inspect

### ISSUE THREAD

**Issue by chrixian** [indexzero/broadway#2]
App.prototype.inspect is currently being set (at the bottom of app.js) to an empty function.. while this doesn't really impact it's general usage, node checks object.inspect for custom inspection info and it does have an annoying side effect of causing objects that are instances of broadway.App to return undefined to the node REPL .. 

To see what I'm talking about run `node` ... and do `var broadway = require('broadway')` then `var app = new broadway.App()` ... now if you type `app` and hit enter it will say undefined.. it of course is not undefined.. `typeof app` returns object ...

**Comment by mlewand** [comment]
Saw the same thing, `inspect` should return something reasonable.
