### ISSUE TITLE
incomplete implementation of features.ensure()?

### ISSUE THREAD

**Issue by rogerz** [indexzero/broadway#26]
in `/lib/broadway/features/index.js`

    exports.ensure = function (app, callback) {
      return callback();
    }

It seems doing nothing except firing the callback. Should there be some test on methods supported by the app?

**Comment by indexzero** [comment]
Super incomplete. The good news is we were trying to do wayyy too much. Now in  [`v1.0.0`](https://github.com/indexzero/broadway/pull/54), we aren't. Either way: I'm going to close this.
