### ISSUE TITLE
Event-driven logging with Winston

### ISSUE THREAD

**Issue by hauraki** [indexzero/broadway#38]
I am trying to use Winston's namespaced logging by emitting events on the broadway app object:

```coffeescript
broadway = require 'broadway'

app = new broadway.App()

app.init (err) ->
  app.log.add 'server',
    console: {
      level: 'error'
      timestamp: true
      colorize: true
    }
  app.emit ['log', 'error'], "log regular error"
  app.emit ['log', 'error', 'server'], "log error in server namespace"
```

I would expect the second error event to be logged by my configured `server` logger, but this is not the case. Digging into the source code of the log plugin, I found the line

```coffeescript
if (ev === 'log') {
    namespace = parts[2] || 'default';
    logger = this.log.get('default');
  }
```
I changed it as follows to get the right logger for the namespace indicated by the event:

```coffeescript
if (ev === 'log') {
    namespace = parts[2] || 'default';
    logger = this.log.get(namespace);
  }
```
Is this the right approach or am I missing something here? I'd be happy to submit a pull request!

**Comment by indexzero** [comment]
A lot has changed in [`v1.0.0`](https://github.com/indexzero/broadway/pull/54), so I'm going to close this. Would love to get your feedback on the new API!
