### ISSUE TITLE
Cannot add namespaced loggers

### ISSUE THREAD

**Issue by hauraki** [indexzero/broadway#44]
Adding namespaced Winston loggers via configuration seems to be broken. When I set the configuration like this:

    app.config.set("log:namespaces:foo", { console: { colorize: true } });

then I would expect Broadway to configure a logger named `foo` for me with the stated configuration:

    app.log.get("foo").info("Colored output here");

but this is not the case. I believe Broadway's log plugin is not picking up the configuration for namespaced loggers correctly. Probably the cause is here: https://github.com/flatiron/broadway/blob/master/lib/broadway/plugins/log.js#L103

Happy to submit a pull request if this is indeed a bug!

**Comment by indexzero** [comment]
It is likely a bug, but a lot has changed in [`v1.0.0`](https://github.com/indexzero/broadway/pull/54), so I'm going to close this. Would love to get your input on the new API for `v1.0.0`!
