### ISSUE TITLE
Cannot find module 'graceful-fs'

### ISSUE THREAD

**Issue by Marko-Jankovic** [indexzero/broadway#46]
This occurs when I tried to require "broadway" on client side.

I think this is fixed on "rimaf" v2 version which is included on "utile" latest version.

Please, update "broadway" to use "utile" latest version.

Thank you,
Marko Jankovic

**Comment by indexzero** [comment]
This makes sense as we never sorted out the browser support for `broadway@0.x.x`, but a lot has changed in [`v1.0.0`](https://github.com/indexzero/broadway/pull/54), so I'm going to close this. Sorry we couldn't be more helpful!

**Comment by Marko-Jankovic** [comment]
BTW, new broadway looks great! I've already tried it, works great on express 4

**Comment by indexzero** [comment]
Thanks!
