### ISSUE TITLE
Setting default env causing problems

### ISSUE THREAD

**Issue by chjj** [indexzero/broadway#48]
https://github.com/flatiron/broadway/blob/master/lib/broadway/bootstrapper.js#L31

This line has been causing us problems. If there is a config file loaded in nconf as a file store, the above line sets env in the literal store. Every time `config.get('env')` is called, it returns the literal store's value, not the file store's value. This is a major problem when the default `app.env` is `development` and your config file says `"env": "production"`.

**Comment by indexzero** [comment]
A lot has changed in [`v1.0.0`](https://github.com/indexzero/broadway/pull/54), so I'm going to close this.
