### ISSUE TITLE
use it with browserify

### ISSUE THREAD

**Issue by alexserver** [indexzero/broadway#49]
This is more like a feature.

I'd like to use this broadway library with browserify, this means, in the client-side.

To aciheve that, I'd need to get rid of some plugins/libraries, like nconf, which uses fs.

Would you like to help to project ? maybe I could fork this into new one...

Anyway I'm pointing to you because you are the main architechts, I think this tool is very nice and it would be valuable to have it available in client-side.

Regards.

**Comment by indexzero** [comment]
I'm not sure, but a lot has changed in [`v1.0.0`](https://github.com/indexzero/broadway/pull/54), so I'm going to close this.
