### ISSUE TITLE
Broken compatibility

### ISSUE THREAD

**Issue by znetstar** [indexzero/broadway#55]
Broken compatibility with the example found on "http://flatironjs.org/". Could someone provide a transition  guide or something similar?

**Comment by gregpabian** [comment]
I think it won't be possible to make your code done with 0.x to be compatible with 1.x because of breaking change in 90e3399008d5165497eb0121b83c48d30df73ba1
I'd rather consider making a fork of broadway 0.3.6 and maintain it in a separate repo.

**Comment by ialex** [comment]
why did 0.3.6 version was deprecated?

**Comment by btushinde** [comment]
:+1: for some sort of documentation at least. This seems to be a significantly different library than the 0.3.6 version but with a similar goal, which leads to a lot of confusion while attempting to upgrade.

**Comment by ialex** [comment]
i think im going to use ampersand-app for now

**Comment by indexzero** [comment]
Yes. We broke in `1.0.0`. Sorry there isn't a great way to update because of how things changed. Essentially:

- There is no longer an `attach` method 
- Everything is the `init` function.
