### ISSUE TITLE
Overriding `.options()` method from express

### ISSUE THREAD

**Issue by samshull** [indexzero/broadway#60]
Setting the [`options`](https://github.com/indexzero/broadway/blob/master/index.js#L16) object is making it hard to create a route handler for an [`OPTIONS`](http://expressjs.com/api.html#app.METHOD) method request in express.

**Comment by jcrugzz** [comment]
hmm yea this is true, you are forced to do something like `app.router.options()` since we do not have it on the top level

**Comment by indexzero** [comment]
I am fine with changing this to something like `_options`.

**Comment by indexzero** [comment]
Actually lets rename it to `given`

**Comment by indexzero** [comment]
Fixed by #63.
